### ISSUE TITLE
connect to wifi networks using python wifi library  

### ISSUE THREAD

**Issue by vivekanandgoud** [rockymeza/wifi#14]
when i googled this is solution i found.
but it says .

if you want Connecting to a network
In order to connect to a network, you need to set up a scheme for it.

> > > cell = Cell.all('wlan0')[0]
> > > scheme = Scheme.for_cell('wlan0', 'home', cell)
> > > scheme.save()
> > > scheme.activate()
> > > Once you have a scheme saved, you can retrieve it using Scheme.find().
> > > 
> > > scheme = Scheme.find('wlan0', 'home')
> > > scheme.activate()

but this was not working for me
even i do the same above still it gives scheme not define error 
please tell me any one .how to connect to wifi networks by python script..

**Comment by villamarinella** [comment]
ImportError: cannot import name Scheme

**Comment by rockymeza** [comment]
Hi @villamarinella,

If you are experiencing an issue, can you open a new GitHub Issue explaining what you are trying to do and what is going wrong?

Thanks

**Comment by sahebdatta** [comment]
Hi!
I was trying the same to list the ssid using the command
`>>> cell=Cell.all('wlan0')`
but I'm getting something like this...
`>>> cell`
`<map object at 0x76b70e70>`
What is this object and how do I get the ssids using this command?
Also when I try to use the command:
`Cell.all('wlan0')[0]`
I get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'map' object is not subscriptable
`
I'm using RaspberryPi 3 for the project
Any help is appreciated...

**Comment by GR3C0** [comment]
Hi @sahebdatta, you are getting a map as you can see.
When i do a `Cell.all('wlan0')` i do with this `[]` because it give to you a list. 

If you wanna access to an element of the list just put `cell[i]` (i is the number of element index on the list).

this is my all-line of code:
`wifi_list = [cell for cell in wifi.Cell.all('wlan0')]`
and then:
` wifi_to_connect = [cell for cell in wifi_list if cell.ssid == wifi_name][0]`
