### ISSUE TITLE
wifi disconnect?

### ISSUE THREAD

**Issue by shunfan** [rockymeza/wifi#31]
wifi now can only connect to a wifi, how about disconnecting from a wifi?

**Comment by Jonnycake** [comment]
I think the reason that the `dhclient -r wlan0` command isn't working for you @rockymeza is because you have NetworkManager (or some other network management daemon) running.  Run `ps -Af | grep NetworkManager` and you should see it.  Depending on how new your install is you will either have to run `/etc/init.d/network-manager stop` or `initctl stop network-manager` (both require root).  You can then use `wifi connect` and then the dhclient command should work.  If I get a chance I'll fork and submit a pull request to implement the deactivate() function and disconnect comand.

**Comment by rockymeza** [comment]
Moving conversation to #58.
