### ISSUE TITLE
interface doesn't support scanning

### ISSUE THREAD

**Issue by voladoddi** [rockymeza/wifi#61]
I'm trying to use the command line to run *#wifi scan* but I get the following error : 
Error: wlan0     Interface doesn't support scanning.

Ubuntu version is 12.04 LTS

**Comment by rockymeza** [comment]
Hi!

I'm sorry you are running into issues. Can you send me the output of:

    sudo iwlist wlan0 scan

**Comment by voladoddi** [comment]
It's the same message I get even if I'm root/superuser. I was wondering if this has anything to do with the fact that Ubuntu on my system is on a virtual machine?

**Comment by rockymeza** [comment]
Oh! You are running Ubuntu inside something like Virtualbox? Yeah, since the OS doesn't really have access to the hardware, we can't really get there. What is your host machine?

**Comment by voladoddi** [comment]
Host is Mac. My interface name there is "en1". 
Tried using that on linux but just doesn't work.

Maybe there is a way to access interfaces using linux even though it's a virtual machine but I don't know yet.

I just used an inbuilt diagnostic tool from Apple and called it from command line for now.

**Comment by rockymeza** [comment]
I don't think I've seen anybody try to do that before. Currently, this library only supports linux (on the host OS, I guess) because it uses a bunch of the linux wireless-tools.

I don't know if there are compatible libraries on mac, but if there are, I would be super happy to try to work them in. What was the diagnostic tool you used?

Thanks for trying!
